### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by akohlbre** [citp/news-disinformation-study#83]
Modules needing updates:

- [ ] PageClassification
- [ ] LinkResolution
- [ ] SocialMediaLinkSharing

**Comment by jonathanmayer** [comment]
Closing this issue because it's now covered on the `web-science` repo.

* `pageClassification`: https://github.com/mozilla-rally/web-science/issues/11 
* `linkResolution`: https://github.com/mozilla-rally/web-science/issues/21
* `socialMediaLinkSharing`: https://github.com/mozilla-rally/web-science/issues/17
