### ISSUE TITLE
Migrate to bundled WebScience library

### ISSUE THREAD

**Issue by jonathanmayer** [citp/news-disinformation-study#92]
After the Rally launch of this study, we should migrate to a dependency on the bundled version of the WebScience library: https://github.com/mozilla-rally/web-science

That'll require a lot of refactoring and QA.

**Comment by akohlbre** [comment]
Update: we're going to do this before the Rally launch, rather than after. I'm working on the migration in the [ws-migration](https://github.com/citp/news-disinformation-study/tree/ws-migration) branch.

A not-yet-exhaustive list of changes to be made:

- [ ] Workers for page classification (working, but need to change the rollup)
- [ ] Worker for data aggregation
- [ ] Indexed storage (mostly working, needs polish)
- [ ] New survey API
- [ ] Myriad small changes (lowercasing, renamed exports, etc) (mostly done... I think. I keep finding more :smiley: )
- [ ] QA testing

**Comment by rhelmer** [comment]
@akohlbre how are things going, do you expect to merge https://github.com/citp/news-disinformation-study/tree/ws-migration to `main` in the near future? We're starting to do reviews on the Mozilla side so I'd like to make sure I'm looking in the right place :)

**Comment by akohlbre** [comment]
Migration is now merged to `main` -- ready for review.
